version: "3.4"
services:
  db:
    container_name: db
    image: mariadb:10.4.26
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: ${DB_EMPTY_ROOT_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_RANDOM_ROOT_PASSWORD: ""
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - "~/Docker/mysql:/var/lib/mysql"
    networks:
      - uptime_network

  influxdb:
    container_name: influxdb
    image: influxdb:latest
    ports:
      - "127.0.0.1:8086:8086"
    volumes:
      - "~/Docker/influxdb:/var/lib/influxdb2"
    networks:
      - uptime_network

  uptime:
    container_name: uptime_checker
    build: .
    ports:
      - "127.0.0.1:7000:7000"
    depends_on:
      - db
      - influxdb
      - redis
    networks:
      - uptime_network
  
  queue-worker:
    container_name: uptime_queue_worker
    build:
      context: .
      dockerfile: ./Dockerfile-worker
    depends_on:
      - db
      - redis
    networks:
      - uptime_network

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    ports:
      - "127.0.0.1:3000:8080"
    volumes:
      - "./doc/swagger/swagger.yml:/swagger.yaml"
    environment:
      SWAGGER_JSON: "/swagger.yaml"
    depends_on:
      - uptime
    networks:
      - uptime_network

  redis:
    container_name: redis
    image: redis:7.2.2
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - "~/Docker/influxdb:/var/lib/redis"
    networks:
      - uptime_network

networks:
  uptime_network:
    name: uptime_network
    driver: bridge