version: "3.4"
services:
  db:
    container_name: db
    image: mariadb:10.4.26
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: ${DB_EMPTY_ROOT_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_RANDOM_ROOT_PASSWORD: ""
    ports:
      - "3306:3306"
    volumes:
      - "~/Docker/mysql:/var/lib/mysql"

  influxdb:
    container_name: influxdb
    image: influxdb:latest
    ports:
      - "8086:8086"
    volumes:
      - "~/Docker/influxdb:/var/lib/influxdb2"

  uptime:
    container_name: uptime_checker
    build: .
    restart: always
    ports:
      - "7000:7000"
    environment:
      DB_HOST: db
      INFLUXDB_HOST: influxdb
    depends_on:
      - db
      - influxdb
      - redis

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    ports:
      - "3000:8080"
    volumes:
      - "./doc/swagger/swagger.yml:/swagger.yaml"
    environment:
      SWAGGER_JSON: "/swagger.yaml"
    depends_on:
      - uptime

  redis:
    container_name: redis
    image: redis:7.2.2
    ports:
      - "3679:3679"
    volumes:
      - "~/Docker/influxdb:/var/lib/redis"
